parameters:
    config:
        hostname: dev.kzen.pro
        defaultPhpVersion: 7.4
        defaultWebroot: public
        dockerBin: /usr/local/bin/docker
        brewBin: /usr/local/bin/brew
        caddyFile: /usr/local/etc/Caddyfile
        caddyDir: '$HOME/Library/Application Support/Caddy'
        caddyService: caddy
        fpmProxies:
            '8.0': 'localhost:9180'
            '7.4': 'localhost:9174'
            '7.3': 'localhost:9173'
            '7.2': 'localhost:9172'
            '7.1': 'localhost:9171'
            '7.0': 'localhost:9170'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $ftlConfig: '%config%'

    App\Commands\:
        resource: 'src/Commands'
        tags: ['console.command']

    App\Service\:
        resource: 'src/Service'

    App\Service\Config:
        factory: ['App\Service\Config', 'createConfig']

    App\Service\Caddy:
        factory: ['App\Service\Caddy', 'create']
